# Application Name
spring.application.name=sb-ecom

# H2 Database Configuration (In-memory database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
  # Automatically updates the schema based on entity classes
spring.jpa.show-sql=true
  # Logs SQL queries to the console
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# H2 SQL dialect

# Spring JPA/Hibernate initialization
spring.jpa.defer-datasource-initialization=true
  # Defers datasource initialization until after beans are created

# H2 Console Configuration (Optional for browsing the database)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Data Initialization (Optional)
# If you need to run some scripts, use this for SQL scripts like data.sql, but you're not using schema.sql
# spring.sql.init.mode=always  # This is optional if you want to run data.sql at startup
logging.level.com.ecommerce.project.controller=DEBUG
project.image=images/